name: Are Notebooks Cleared

on:
  workflow_call:
    inputs:
      paths:
        required: false
        type: string
        default: "**/*.ipynb"

env:
  SCRIPT_DIR: "${{ github.workspace }}/scripts"
  SCRIPT_NAME: "are_notebooks_cleared.bash"
  REPO_URL: "https://raw.githubusercontent.com/kvn-dtrx/git-hub-automatisation/main/scripts"

jobs:
  are-notebooks-cleared:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Provide Script
        run: |
          SCRIPT_PATH="${SCRIPT_DIR}/${SCRIPT_NAME}"
          mkdir -p "${SCRIPT_DIR}"
          curl -o "${SCRIPT_PATH}" "${REPO_URL}/${SCRIPT_NAME}"
          chmod +x "${SCRIPT_PATH}"

      - name: Are Notebooks Cleared
        run: ${SCRIPT_DIR}/${SCRIPT_NAME} "${{ inputs.paths }}"
