name: Are Notebooks Cleared

on:
  workflow_call:
    inputs:
      base_sha:
        required: true
        type: string
      head_sha:
        required: true
        type: string
      # paths:
      #   required: false
      #   type: string
      #   default: "**/*.ipynb"

jobs:
  are-notebooks-cleared:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Core Task
        env:
          SCRIPT_URL: "https://raw.githubusercontent.com/kvn-dtrx/git-hub-automatisation/main/scripts/ci/are_notebooks_cleared.bash"
          BASE_SHA: ${{ inputs.base_sha }}
          HEAD_SHA: ${{ inputs.head_sha }}
        run: |
          curl -fslL "${SCRIPT_URL}" -o tmp_script
          ./tmp_script
      # - name: Run Core Task
      #   run: |
      #     curl -fsSL -o check_notebooks.sh https://raw.githubusercontent.com/kvn-dtrx/git-hub-automatisation/main/scripts/are_notebooks_cleared.bash
      #     bash check_notebooks.sh "${{ inputs.paths }}"
