name: Do Links Work

on:
  workflow_call:

env:
  SCRIPT_DIR: "${{ github.workspace }}/scripts"
  SCRIPT_NAME: "are_notebooks_cleared.bash"
  REPO_URL: "https://raw.githubusercontent.com/kvn-dtrx/git-hub-automatisation/main/scripts"

jobs:
  do-links-work:
    runs-on: ubuntu-latest
    permissions:
      # required for peter-evans/create-issue-from-file
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Core Task
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          args: --verbose "**/*.md" "**/*.tex" "**/*.txt"
          fail: false
          # NOTE: Secret must be added to the repository. Can be done on CLI via:
          # gh secret set GH_LYCHEE_TOKEN --body "cryptic-token" --repo "repo-name"
          token: ${{ secrets.GH_LYCHEE_TOKEN }}

      - name: Create Issue
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
