name: Does make Work

on:
  workflow_call:

jobs:
  does-make-work-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          sudo apt-get install -y curl
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y zlib1g-dev
          sudo apt-get install -y libbz2-dev
          sudo apt-get install -y libreadline-dev
          sudo apt-get install -y libsqlite3-dev
      - name: Setup Python Environment
        run: |
          curl https://pyenv.run | bash
          echo "PYENV_ROOT=$HOME/.pyenv" >> "${GITHUB_ENV}"
          # export PYENV_ROOT="${HOME}/.pyenv"
          echo "PATH=$HOME/.pyenv/bin:${PATH}" >> "${GITHUB_ENV}"
          # export PATH="${PYENV_ROOT}/bin:${PATH}"
          eval "$(pyenv init --path)"
          # eval "$(pyenv init -)"
          pyenv install 3.11.3
      - name: Run Core Task
        run: make basic-unix

  does-make-work-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          brew install pyenv
          brew install make
      - name: Setup Python Environment
        run: |
          echo "PYENV_ROOT=${HOME}/.pyenv" >> "${GITHUB_ENV}"
          echo "PATH=${PYENV_ROOT}/bin:$PATH" >> "${GITHUB_ENV}"
          pyenv install 3.11.3
      - name: Run Core Task
        run: make basic-unix

  does-make-work-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          choco install pyenv-win -y
          choco install make -y
        shell: powershell
      - name: Setup Python Environment
        run: |
          $pyenvRoot = "C:\tools\pyenv-win"
          echo "PYENV=$pyenvRoot" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV
          # $env:PYENV = $pyenvRoot
          echo "PATH=$pyenvRoot\bin;$pyenvRoot\shims;$env:PATH" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV
          # $env:PATH = "$pyenvRoot\bin;$pyenvRoot\shims;$env:PATH"
          pyenv install 3.11.3
        shell: powershell
      - name: Run Core Task
        run: |
          make basic-win
        shell: powershell
